# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Collections
collections:
- admin_docs
- client_docs
- server_docs
- implementation

# Setup
title:            SKDS
tagline:          'Secure Key Distribution System'
description:      'A system for securely distributing secret keys across a large number of systems.'
url:              http://getskds.io/
baseurl:          /

author:
  name:           'James Findley'
  email:          'skds@fastmail.fm'

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/jfindley/skds
